In [16]:
loansdf <- read.csv('data/prosperLoanData.csv')

In [32]:
library(tidyverse)
#library(GGally) need this for scatterplot

ERROR: Error in library(GGally): there is no package called 'GGally'

In [29]:
loansdf %>%
select(one_of(interesting_columns))

       ListingCreationDate           Term LoanStatus             BorrowerAPR
1      2007-08-26 19:09:29.263000000 36   Completed              0.16516
2      2014-02-27 08:28:07.900000000 36   Current                0.12016
3      2007-01-05 15:00:47.090000000 36   Completed              0.28269
4      2012-10-22 11:02:35.010000000 36   Current                0.12528
5      2013-09-14 18:38:39.097000000 36   Current                0.24614
6      2013-12-14 08:26:37.093000000 60   Current                0.15425
7      2013-04-12 09:52:56.147000000 36   Current                0.31032
8      2013-05-05 06:49:27.493000000 36   Current                0.23939
9      2013-12-02 10:43:39.117000000 36   Current                0.07620
10     2013-12-02 10:43:39.117000000 36   Current                0.07620
11     2012-05-10 07:04:01.577000000 60   Current                0.27462
12     2007-10-09 20:28:33.640000000 36   Completed              0.15033
13     2013-12-15 20:01:10.757000000 36   Past Due (1-15 days)   0.17969
14     2013-07-15 16:28:28.087000000 36   Current                0.13138
15     2013-04-19 11:17:41.700000000 60   Current                0.11695
16     2012-04-10 09:14:46.297000000 36   Defaulted              0.35797
17     2013-07-16 12:42:48.680000000 60   Current                0.30748
18     2006-08-15 12:21:09.433000000 36   Chargedoff             0.13202
19     2013-02-20 03:48:37.470000000 36   Current                0.12528
20     2013-08-21 06:49:02.093000000 60   Current                0.24754
21     2013-11-22 11:35:02.987000000 36   Current                0.16732
22     2007-11-30 20:33:49.227000000 36   Completed              0.21488
23     2013-01-30 09:36:13.783000000 36   Current                0.35356
24     2013-04-22 13:29:19.073000000 36   Defaulted              0.28032
25     2013-12-03 11:34:46.127000000 36   Current                0.19859
26     2013-10-02 14:31:09.157000000 36   Current                0.30182
27     2013-02-12 18:07:31.690000000 60   Completed              0.30748
28     2010-06-16 16:23:44.533000000 36   Completed              0.11296
29     2013-11-02 16:01:28.050000000 36   Current                0.20268
30     2013-12-17 09:18:33.220000000 36   Current                0.15223
...    ...                           ...  ...                    ...
113908 2013-11-09 06:55:05.690000000 36   Current                0.35356
113909 2010-11-29 10:40:09.730000000 36   Completed              0.35858
113910 2012-09-08 10:34:38.837000000 60   Current                0.27554
113911 2014-01-24 19:56:49.960000000 36   Current                0.32446
113912 2013-11-15 11:42:47.540000000 36   Current                0.25330
113913 2013-12-16 16:36:00.990000000 36   Current                0.06726
113914 2010-04-25 15:13:27.963000000 36   Completed              0.12410
113915 2006-08-09 14:34:40.010000000 36   Defaulted              0.25757
113916 2008-07-29 05:22:29.390000000 36   Completed              0.22237
113917 2012-11-08 20:07:36.600000000 36   Current                0.33286
113918 2013-11-23 04:52:50.057000000 36   Current                0.32446
113919 2008-06-19 12:02:53.300000000 36   Defaulted              0.12201
113920 2013-05-07 18:49:59.750000000 36   Current                0.27285
113921 2013-06-11 05:49:40.247000000 36   Current                0.35356
113922 2005-11-09 20:44:28.847000000 36   Completed                   NA
113923 2008-08-08 16:58:54.760000000 36   Completed              0.15094
113924 2008-09-10 08:26:30.537000000 36   Completed              0.22378
113925 2012-10-20 19:15:52.670000000 60   Current                0.17317
113926 2013-04-25 13:54:45.017000000 36   Current                0.31032
113927 2006-08-01 10:31:31.143000000 36   Defaulted              0.29776
113928 2008-04-30 21:25:19.670000000 36   Completed              0.07469
113929 2011-06-06 19:02:44.443000000 36   Completed              0.22362
113930 2013-07-06 17:40:01.657000000 36   Completed              0.30285
113931 2013-07-08 10:24:49.700000000 36   Current                0.20053
113932 2014-01-16 20:13:08.040000000 60   Current                0.15016
113933 2013-04-14 05:55:02.663000000 36   Current                0.22354
113934 2011-11-03 20:42:55.333000000 36   FinalPaymentInProgress 0.13220
113935 2013-12-13 05:49:12.703000000 60   Current                0.23984
113936 2011-11-14 13:18:26.597000000 60   Completed              0.28408
113937 2014-01-15 09:27:37.657000000 36   Current                0.13189
       BorrowerRate LenderYield EstimatedEffectiveYield EstimatedReturn
1      0.1580       0.1380           NA                      NA
2      0.0920       0.0820      0.07960                 0.05470
3      0.2750       0.2400           NA                      NA
4      0.0974       0.0874      0.08490                 0.06000
5      0.2085       0.1985      0.18316                 0.09066
6      0.1314       0.1214      0.11567                 0.07077
7      0.2712       0.2612      0.23820                 0.11070
8      0.2019       0.1919      0.17830                 0.09840
9      0.0629       0.0529      0.05221                 0.04231
10     0.0629       0.0529      0.05221                 0.04231
11     0.2489       0.2389      0.23320                 0.14420
12     0.1325       0.1225           NA                      NA
13     0.1435       0.1335      0.12640                 0.07400
14     0.1034       0.0934      0.09050                 0.06310
15     0.0949       0.0849      0.08270                 0.06030
16     0.3177       0.3077      0.28960                 0.12460
17     0.2809       0.2709      0.24730                 0.12480
18     0.1250       0.1175           NA                      NA
19     0.0974       0.0874      0.08490                 0.06000
20     0.2225       0.2125      0.19520                 0.09270
21     0.1314       0.1214      0.11567                 0.07077
22     0.2075       0.1975           NA                      NA
23     0.3134       0.3034      0.27600                 0.11850
24     0.2419       0.2319      0.21260                 0.10510
25     0.1620       0.1520      0.14256                 0.07766
26     0.2629       0.2529      0.23057                 0.10307
27     0.2809       0.2709      0.24730                 0.12480
28     0.0920       0.0820      0.06080                 0.06080
29     0.1660       0.1560      0.14661                 0.08421
30     0.1239       0.1139      0.10900                 0.06910
...    ...          ...         ...                     ...
113908 0.3134       0.3034      0.27598                 0.11348
113909 0.3220       0.3120      0.15570                 0.15570
113910 0.2498       0.2398      0.23410                 0.14920
113911 0.2850       0.2750      0.25006                 0.10256
113912 0.2155       0.2055      0.18917                 0.09167
113913 0.0605       0.0505      0.05000                 0.04260
113914 0.1030       0.0930      0.07170                 0.07170
113915 0.2500       0.2450           NA                      NA
113916 0.2000       0.1900           NA                      NA
113917 0.2932       0.2832      0.25750                 0.11500
113918 0.2850       0.2750      0.25006                 0.10256
113919 0.1080       0.0980           NA                      NA
113920 0.2346       0.2246      0.20640                 0.10390
113921 0.3134       0.3034      0.27600                 0.11850
113922 0.0400       0.0350           NA                      NA
113923 0.1295       0.1195           NA                      NA
113924 0.2089       0.1989           NA                      NA
113925 0.1499       0.1399      0.13460                 0.09970
113926 0.2712       0.2612      0.23820                 0.11070
113927 0.2900       0.2850           NA                      NA
113928 0.0679       0.0579           NA                      NA
113929 0.1899       0.1799      0.17570                 0.11470
113930 0.2639       0.2539      0.23180                 0.10930
113931 0.1639       0.1539      0.14520                 0.08780
113932 0.1274       0.1174      0.11210                 0.06970
113933 0.1864       0.1764      0.16490                 0.09500
113934 0.1110       0.1010      0.10070                 0.08070
113935 0.2150       0.2050      0.18828                 0.08578
113936 0.2605       0.2505      0.24450                 0.15950
113937 0.1039       0.0939      0.09071                 0.06081
       ProsperScore ListingCategory..numeric. BorrowerState
1      NA            0                        CO
2       7            2                        CO
3      NA            0                        GA
4       9           16                        GA
5       4            2                        MN
6      10            1                        NM
7       2            1                        KS
8       4            2                        CA
9       9            7                        IL
10     11            7                        IL
11      7            1                        MD
12     NA            0
13      4            1                        AL
14      8            1                        AZ
15      8            1                        VA
16      5           13                        FL
17      4            6                        CA
18     NA            0
19      7            1                        PA
20      8            1                        OR
21      7            1                        MN
22     NA            0                        MI
23      2            1                        NY
24      5           15                        IL
25      5            1                        LA
26      3           15                        CA
27      3            1                        NY
28      9            1                        CO
29      4            2                        PA
30      6            1                        LA
...    ...          ...                       ...
113908  2            1                        AZ
113909  5            3                        NY
113910  7            2                        FL
113911  2            1                        TX
113912  3           14                        MD
113913 11            2                        MN
113914  9            1                        WA
113915 NA            0                        CA
113916 NA            7                        MA
113917  6           13                        FL
113918  2            1                        OH
113919 NA            4                        CA
113920  3            2                        IL
113921  2            1                        NJ
113922 NA            0
113923 NA            5                        GA
113924 NA            1                        MS
113925  8           13                        WA
113926  2            1                        NY
113927 NA            0                        CA
113928 NA            4                        WA
113929  6            3                        CO
113930  3            2                        FL
113931  6            1                        IN
113932  6            3                        IL
113933  5            1                        IL
113934  8            7                        PA
113935  3            1                        TX
113936  5            2                        GA
113937  7            1                        NY
       Occupation              EmploymentStatus EmploymentStatusDuration
1      Other                   Self-employed      2
2      Professional            Employed          44
3      Other                   Not available     NA
4      Skilled Labor           Employed         113
5      Executive               Employed          44
6      Professional            Employed          82
7      Sales - Retail          Employed         172
8      Laborer                 Employed         103
9      Food Service            Employed         269
10     Food Service            Employed         269
11     Fireman                 Employed         300
12     Waiter/Waitress         Full-time         19
13     Sales - Retail          Employed           1
14     Construction            Employed          98
15     Computer Programmer     Employed          35
16     Other                   Other            121
17     Professional            Full-time        133
18     Professional            Not available     NA
19     Sales - Commission      Employed         179
20     Laborer                 Employed          18
21     Retail Management       Employed         175
22     Professional            Full-time         36
23     Other                   Other             68
24     Skilled Labor           Employed           3
25     Other                   Employed          91
26     Engineer - Mechanical   Employed          15
27     Sales - Commission      Employed          25
28     Executive               Full-time         10
29     Military Enlisted       Employed          48
30     Other                   Employed          16
...    ...                     ...              ...
113908 Sales - Retail          Employed          86
113909 Sales - Commission      Employed          68
113910 Clerical                Employed         265
113911 Executive               Employed           8
113912 Other                   Employed          51
113913 Scientist               Employed         102
113914 Analyst                 Full-time         19
113915                                           NA
113916 Other                   Full-time         43
113917 Professional            Employed         149
113918 Clerical                Employed          32
113919 Social Worker           Full-time        252
113920 Other                   Other             12
113921 Retail Management       Employed         110
113922                                           NA
113923 Other                   Full-time        115
113924 Clergy                  Full-time         83
113925 Other                   Employed          56
113926 Homemaker               Employed          31
113927 Other                   Not available     NA
113928 Executive               Full-time         69
113929 Other                   Full-time         22
113930 Accountant/CPA          Employed          25
113931 Professional            Employed          85
113932 Analyst                 Employed          12
113933 Food Service Management Employed         246
113934 Professional            Employed          21
113935 Other                   Employed          84
113936 Food Service            Full-time         94
113937 Professor               Employed         244
       CreditScoreRangeUpper IncomeRange    Investors
1      659                   $25,000-49,999 258
2      699                   $50,000-74,999   1
3      499                   Not displayed   41
4      819                   $25,000-49,999 158
5      699                   $100,000+       20
6      759                   $100,000+        1
7      699                   $25,000-49,999   1
8      719                   $25,000-49,999   1
9      839                   $25,000-49,999   1
10     839                   $25,000-49,999   1
11     659                   $75,000-99,999  19
12     659                   $1-24,999       53
13     699                   $25,000-49,999   1
14     759                   $50,000-74,999 171
15     759                   $100,000+      371
16     719                   $50,000-74,999  10
17     659                   $75,000-99,999   8
18     779                   Not displayed   85
19     759                   $75,000-99,999 303
20     699                   $25,000-49,999   1
21     679                   $50,000-74,999   1
22     639                   $25,000-49,999  53
23     719                   $1-24,999       94
24     699                   $25,000-49,999  30
25     679                   $25,000-49,999   1
26     699                   $75,000-99,999   3
27     679                   $25,000-49,999  37
28     719                   $75,000-99,999 121
29     739                   $25,000-49,999   1
30     759                   $100,000+        1
...    ...                   ...            ...
113908 659                   $25,000-49,999   3
113909 719                   $25,000-49,999  98
113910 819                   $25,000-49,999   9
113911 659                   $100,000+        1
113912 679                   $25,000-49,999   1
113913 819                   $25,000-49,999   1
113914 799                   $100,000+      265
113915 539                   Not displayed    1
113916 639                   $50,000-74,999 135
113917 679                   $50,000-74,999  87
113918 679                   $1-24,999        1
113919 759                   $50,000-74,999 173
113920 699                   $25,000-49,999   1
113921 759                   $50,000-74,999   1
113922  NA                   Not displayed    1
113923 659                   $50,000-74,999 145
113924 719                   $25,000-49,999 270
113925 659                   $25,000-49,999  83
113926 699                   $25,000-49,999   1
113927 559                   Not displayed   39
113928 779                   $100,000+      194
113929 759                   $25,000-49,999  25
113930 679                   $50,000-74,999  26
113931 699                   $75,000-99,999  52
113932 819                   $75,000-99,999   1
113933 719                   $50,000-74,999   1
113934 719                   $75,000-99,999  22
113935 719                   $25,000-49,999 119
113936 699                   $25,000-49,999 274
113937 699                   $50,000-74,999   1

In [31]:
help(package = 'GGally')

ERROR: Error in find.package(pkgName, lib.loc, verbose = verbose): there is no package called 'GGally'

In [28]:
#Create list of intersesting variables to scattermatrix. 
interesting_columns <- c('ListingCreationDate', 'Term', 'LoanStatus', 'BorrowerAPR', 'BorrowerRate', 'LenderYield',
                        'EstimatedEffectiveYield', 'EstimatedReturn', 'ProsperScore', 'ListingCategory..numeric.',
                        'BorrowerState', 'Occupation', 'EmploymentStatus', 'EmploymentStatusDuration', 'CreditScoreRangeUpper',
                        'IncomeRange', 'Investors')

'data.frame':	113937 obs. of  81 variables:
 $ ListingKey                         : Factor w/ 113066 levels "00003546482094282EF90E5",..: 7180 7193 6647 6669 6686 6689 6699 6706 6687 6687 ...
 $ ListingNumber                      : int  193129 1209647 81716 658116 909464 1074836 750899 768193 1023355 1023355 ...
 $ ListingCreationDate                : Factor w/ 113064 levels "2005-11-09 20:44:28.847000000",..: 14184 111894 6429 64760 85967 100310 72556 74019 97834 97834 ...
 $ CreditGrade                        : Factor w/ 9 levels "","A","AA","B",..: 5 1 8 1 1 1 1 1 1 1 ...
 $ Term                               : int  36 36 36 36 36 60 36 36 36 36 ...
 $ LoanStatus                         : Factor w/ 12 levels "Cancelled","Chargedoff",..: 3 4 3 4 4 4 4 4 4 4 ...
 $ ClosedDate                         : Factor w/ 2803 levels "","2005-11-25 00:00:00",..: 1138 1 1263 1 1 1 1 1 1 1 ...
 $ BorrowerAPR                        : num  0.165 0.12 0.283 0.125 0.246 ...
 $ BorrowerRate                       : num  0.158 0.092 0.275 0.0974 0.2085 ...
 $ LenderYield                        : num  0.138 0.082 0.24 0.0874 0.1985 ...
 $ EstimatedEffectiveYield            : num  NA 0.0796 NA 0.0849 0.1832 ...
 $ EstimatedLoss                      : num  NA 0.0249 NA 0.0249 0.0925 ...
 $ EstimatedReturn                    : num  NA 0.0547 NA 0.06 0.0907 ...
 $ ProsperRating..numeric.            : int  NA 6 NA 6 3 5 2 4 7 7 ...
 $ ProsperRating..Alpha.              : Factor w/ 8 levels "","A","AA","B",..: 1 2 1 2 6 4 7 5 3 3 ...
 $ ProsperScore                       : num  NA 7 NA 9 4 10 2 4 9 11 ...
 $ ListingCategory..numeric.          : int  0 2 0 16 2 1 1 2 7 7 ...
 $ BorrowerState                      : Factor w/ 52 levels "","AK","AL","AR",..: 7 7 12 12 25 34 18 6 16 16 ...
 $ Occupation                         : Factor w/ 68 levels "","Accountant/CPA",..: 37 43 37 52 21 43 50 29 24 24 ...
 $ EmploymentStatus                   : Factor w/ 9 levels "","Employed",..: 9 2 4 2 2 2 2 2 2 2 ...
 $ EmploymentStatusDuration           : int  2 44 NA 113 44 82 172 103 269 269 ...
 $ IsBorrowerHomeowner                : Factor w/ 2 levels "False","True": 2 1 1 2 2 2 1 1 2 2 ...
 $ CurrentlyInGroup                   : Factor w/ 2 levels "False","True": 2 1 2 1 1 1 1 1 1 1 ...
 $ GroupKey                           : Factor w/ 707 levels "","00343376901312423168731",..: 1 1 335 1 1 1 1 1 1 1 ...
 $ DateCreditPulled                   : Factor w/ 112992 levels "2005-11-09 00:30:04.487000000",..: 14347 111883 6446 64724 85857 100382 72500 73937 97888 97888 ...
 $ CreditScoreRangeLower              : int  640 680 480 800 680 740 680 700 820 820 ...
 $ CreditScoreRangeUpper              : int  659 699 499 819 699 759 699 719 839 839 ...
 $ FirstRecordedCreditLine            : Factor w/ 11586 levels "","1947-08-24 00:00:00",..: 8639 6617 8927 2247 9498 497 8265 7685 5543 5543 ...
 $ CurrentCreditLines                 : int  5 14 NA 5 19 21 10 6 17 17 ...
 $ OpenCreditLines                    : int  4 14 NA 5 19 17 7 6 16 16 ...
 $ TotalCreditLinespast7years         : int  12 29 3 29 49 49 20 10 32 32 ...
 $ OpenRevolvingAccounts              : int  1 13 0 7 6 13 6 5 12 12 ...
 $ OpenRevolvingMonthlyPayment        : num  24 389 0 115 220 1410 214 101 219 219 ...
 $ InquiriesLast6Months               : int  3 3 0 0 1 0 0 3 1 1 ...
 $ TotalInquiries                     : num  3 5 1 1 9 2 0 16 6 6 ...
 $ CurrentDelinquencies               : int  2 0 1 4 0 0 0 0 0 0 ...
 $ AmountDelinquent                   : num  472 0 NA 10056 0 ...
 $ DelinquenciesLast7Years            : int  4 0 0 14 0 0 0 0 0 0 ...
 $ PublicRecordsLast10Years           : int  0 1 0 0 0 0 0 1 0 0 ...
 $ PublicRecordsLast12Months          : int  0 0 NA 0 0 0 0 0 0 0 ...
 $ RevolvingCreditBalance             : num  0 3989 NA 1444 6193 ...
 $ BankcardUtilization                : num  0 0.21 NA 0.04 0.81 0.39 0.72 0.13 0.11 0.11 ...
 $ AvailableBankcardCredit            : num  1500 10266 NA 30754 695 ...
 $ TotalTrades                        : num  11 29 NA 26 39 47 16 10 29 29 ...
 $ TradesNeverDelinquent..percentage. : num  0.81 1 NA 0.76 0.95 1 0.68 0.8 1 1 ...
 $ TradesOpenedLast6Months            : num  0 2 NA 0 2 0 0 0 1 1 ...
 $ DebtToIncomeRatio                  : num  0.17 0.18 0.06 0.15 0.26 0.36 0.27 0.24 0.25 0.25 ...
 $ IncomeRange                        : Factor w/ 8 levels "$0","$1-24,999",..: 4 5 7 4 3 3 4 4 4 4 ...
 $ IncomeVerifiable                   : Factor w/ 2 levels "False","True": 2 2 2 2 2 2 2 2 2 2 ...
 $ StatedMonthlyIncome                : num  3083 6125 2083 2875 9583 ...
 $ LoanKey                            : Factor w/ 113066 levels "00003683605746079487FF7",..: 100337 69837 46303 70776 71387 86505 91250 5425 908 908 ...
 $ TotalProsperLoans                  : int  NA NA NA NA 1 NA NA NA NA NA ...
 $ TotalProsperPaymentsBilled         : int  NA NA NA NA 11 NA NA NA NA NA ...
 $ OnTimeProsperPayments              : int  NA NA NA NA 11 NA NA NA NA NA ...
 $ ProsperPaymentsLessThanOneMonthLate: int  NA NA NA NA 0 NA NA NA NA NA ...
 $ ProsperPaymentsOneMonthPlusLate    : int  NA NA NA NA 0 NA NA NA NA NA ...
 $ ProsperPrincipalBorrowed           : num  NA NA NA NA 11000 NA NA NA NA NA ...
 $ ProsperPrincipalOutstanding        : num  NA NA NA NA 9948 ...
 $ ScorexChangeAtTimeOfListing        : int  NA NA NA NA NA NA NA NA NA NA ...
 $ LoanCurrentDaysDelinquent          : int  0 0 0 0 0 0 0 0 0 0 ...
 $ LoanFirstDefaultedCycleNumber      : int  NA NA NA NA NA NA NA NA NA NA ...
 $ LoanMonthsSinceOrigination         : int  78 0 86 16 6 3 11 10 3 3 ...
 $ LoanNumber                         : int  19141 134815 6466 77296 102670 123257 88353 90051 121268 121268 ...
 $ LoanOriginalAmount                 : int  9425 10000 3001 10000 15000 15000 3000 10000 10000 10000 ...
 $ LoanOriginationDate                : Factor w/ 1873 levels "2005-11-15 00:00:00",..: 426 1866 260 1535 1757 1821 1649 1666 1813 1813 ...
 $ LoanOriginationQuarter             : Factor w/ 33 levels "Q1 2006","Q1 2007",..: 18 8 2 32 24 33 16 16 33 33 ...
 $ MemberKey                          : Factor w/ 90831 levels "00003397697413387CAF966",..: 11071 10302 33781 54939 19465 48037 60448 40951 26129 26129 ...
 $ MonthlyLoanPayment                 : num  330 319 123 321 564 ...
 $ LP_CustomerPayments                : num  11396 0 4187 5143 2820 ...
 $ LP_CustomerPrincipalPayments       : num  9425 0 3001 4091 1563 ...
 $ LP_InterestandFees                 : num  1971 0 1186 1052 1257 ...
 $ LP_ServiceFees                     : num  -133.2 0 -24.2 -108 -60.3 ...
 $ LP_CollectionFees                  : num  0 0 0 0 0 0 0 0 0 0 ...
 $ LP_GrossPrincipalLoss              : num  0 0 0 0 0 0 0 0 0 0 ...
 $ LP_NetPrincipalLoss                : num  0 0 0 0 0 0 0 0 0 0 ...
 $ LP_NonPrincipalRecoverypayments    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ PercentFunded                      : num  1 1 1 1 1 1 1 1 1 1 ...
 $ Recommendations                    : int  0 0 0 0 0 0 0 0 0 0 ...
 $ InvestmentFromFriendsCount         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ InvestmentFromFriendsAmount        : num  0 0 0 0 0 0 0 0 0 0 ...
 $ Investors                          : int  258 1 41 158 20 1 1 1 1 1 ...